AWSTemplateFormatVersion: "2010-09-09"
Description: Main stack template

Parameters:
  S3BucketName:
    Type: String

Resources:

  NestedS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/my-demo-nw/s3.yml'
      Parameters:
        S3BucketName: !Ref S3BucketName
   

